// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoListAPI.Data;

#nullable disable

namespace ToDoListAPI.Migrations
{
    [DbContext(typeof(ToDoListDbContext))]
    [Migration("20250820202423_DateAdded")]
    partial class DateAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToDoListAPI.Models.ToDoList", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("toDoLists");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdAt = new DateTime(2025, 8, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            description = "",
                            isCompleted = false,
                            title = "Buy groceries"
                        },
                        new
                        {
                            id = 2,
                            createdAt = new DateTime(2025, 8, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            description = "",
                            isCompleted = true,
                            title = "Walk the dog"
                        },
                        new
                        {
                            id = 3,
                            createdAt = new DateTime(2025, 8, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            description = "",
                            isCompleted = false,
                            title = "Read a book"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
